//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enajenante
    {
        public int id { get; set; }
        public int NumeroAtencion { get; set; }
        public string RunRut { get; set; }
        public decimal PorcentajeDerecho { get; set; }
        public bool DerechoNoAcreditado { get; set; }
    
        public virtual Escritura Escritura { get; set; }
    }
}
