
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UAndes.ICC5103._202301.Models
{

using System;
    using System.Collections.Generic;
    
public partial class enajenante
{

    public int id { get; set; }

    public int numAtencion { get; set; }

    public string runRut { get; set; }

    public decimal porcentajeDerecho { get; set; }

    public bool derechoNoAcreditado { get; set; }



    public virtual escritura escritura { get; set; }

}

}
