//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escritura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Escritura()
        {
            this.Adquiriente = new HashSet<Adquiriente>();
            this.Enajenante = new HashSet<Enajenante>();
        }
    
        public int NumeroAtencion { get; set; }
        public string CNE { get; set; }
        public string Comuna { get; set; }
        public string Manzana { get; set; }
        public string Predio { get; set; }
        public int Fojas { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public string NumeroInscripcion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adquiriente> Adquiriente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enajenante> Enajenante { get; set; }
    }
}
