
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UAndes.ICC5103._202301.Models
{

using System;
    using System.Collections.Generic;
    
public partial class escritura
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public escritura()
    {

        this.adquiriente = new HashSet<adquiriente>();

        this.enajenante = new HashSet<enajenante>();

    }


    public int numAtencion { get; set; }

    public string cne { get; set; }

    public string comuna { get; set; }

    public string manzana { get; set; }

    public string predio { get; set; }

    public int fojas { get; set; }

    public System.DateTime fechaInscripcion { get; set; }

    public string numInscripcion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<adquiriente> adquiriente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<enajenante> enajenante { get; set; }

}

}
