
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UAndes.ICC5103._202301.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Multipropietario
{

    public int Id { get; set; }

    public string Comuna { get; set; }

    public string Manzana { get; set; }

    public string Predio { get; set; }

    public string RunRut { get; set; }

    public decimal PorcentajeDerecho { get; set; }

    public int Fojas { get; set; }

    public System.DateTime AñoInscripcion { get; set; }

    public int NumeroInscripcion { get; set; }

    public System.DateTime FechaInscripcion { get; set; }

    public System.DateTime AñoVigenciaInicial { get; set; }

    public System.DateTime AñoVigenciaFinal { get; set; }

}

}
